[rej]=eegplot(EEG.data,'srate',256,'eloc_file',EEG.chanlocs,'events',EEG.event,'ploteventdur','on','command',['[EEGTMP LASTCOM] = eeg_eegrej(EEG,eegplot2event(TMPREJ, -1));' ...
'  [ALLEEG EEG CURRENTSET tmpcom] = pop_newset(ALLEEG, EEGTMP, CURRENTSET);' ...
'     eeglab(''redraw'');' ...
'clear EEGTMP tmpcom;']);